added step for checking integration test IDs
In order to ensure every integration test has an ID linked to
it, a CI step executes a dry run for the generation and checks
the result.

Signed-off-by: Michael Engel <mengel@redhat.com>

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -73,6 +73,12 @@ jobs:
         with:
           name: rpm-artifacts
           path: 'tests/bluechi-rpms'
+      
+      - name: Check integration test IDs
+        run: |
+          cd tests
+          tmt test id --dry | grep "New id" && echo "Found integration tests with missing ID. Please generate Test-IDs." && exit 1
+          cd ..
 
       - name: Run integration tests
         run: |
